name: Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENV: ${{ secrets.ENV }}
      USER_LOGIN: ${{ secrets.USER_LOGIN }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      USER_FIRST_NAME: ${{ secrets.USER_FIRST_NAME }}
      USER_LAST_NAME: ${{ secrets.USER_LAST_NAME }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_IRC_NICK: ${{ secrets.USER_IRC_NICK }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test || true

      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30

      - name: Install Allure globally
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: npx allure generate my-allure-results -o allure-report --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: allure-report
